# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1inputsetverificationdelapparitiondelencart:
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1inputsetverificationdelapparitiondelencart(self):
    self.driver.get("http://localhost:5173/")
    self.driver.set_window_size(1227, 640)
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("Mon nom")
    self.driver.find_element(By.CSS_SELECTOR, "select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "select")
    dropdown.find_element(By.XPATH, "//option[. = 'Warrior']").click()
    elements = self.driver.find_elements(By.ID, "divCaracteristiques")
    assert len(elements) > 0
    assert self.driver.find_element(By.ID, "caracteristiquesStrength").text == "Strength : 10"
    assert self.driver.find_element(By.ID, "caracteristiquesIntelligence").text == "Intelligence : 5"
    assert self.driver.find_element(By.ID, "caracteristiquesLuck").text == "Luck : 3"
  
